### ISSUE TITLE
V1.1 TO-DO code changes by 03/03/19

### ISSUE THREAD

**Issue by ditan96** [cs2103-ay1819s2-w10-2/main#7]
@ditan96 
- [x] Refactoring persons to employees
- [ ] Refactoring tags to skills (postpone to milestone v1.2)

@shunnizuka 
- [x] find project (still need system tests)
- [x] find employee
- [ ] find skill (postpone to milestone v1.2)

@jothipillay 
- [x] add employee
- [x] add project

@dehui333
- [x] delete employee
- [x] delete project

@jeffgan96 
- [x] list employees
- [x] list projects

Additional (TBC)
- [ ] Remove history command
- [ ] Remove undo command
- [ ] Remove redo command
- [ ] Remove clear command
- [ ] Remove select command
